#!/bin/sh
#################################################################
#
#   Copyright 2009-2010 Daniel Schopf
#             Institute for Theoretical and Applied Physics
#             University of Stuttgart, D-70550 Stuttgart, Germany
#             http://www.itap.physik.uni-stuttgart.de/
#
#################################################################
#
#   This file is part of potfit.
#
#   potfit is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   potfit is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with potfit; if not, see <http://www.gnu.org/licenses/>.
#
#################################################################

if [ $# -eq 0 ]; then
	echo "Usage: list_config.sh FILENAME"
	exit
elif [ $# -ge 2 ]; then
	echo "More then 1 file given on command line. Only $1 will be interpreted"
	echo
fi
if [ ! -e "$1" ]; then
	echo "File $1 does not exists, aborting"
	echo
	exit 2;
fi
grep -n -e \#N -e generated -e \#F -e \#W $1 | awk -v file=$1 'BEGIN{i=0}
{
	gsub(":"," ");
	line=$1;
	n_atoms=$3;
	getline;
	gsub(":"," ");
	printf "%3d: ",i;
	if ($2=="#F") {
		printf "no information found in %s\n",file;
		printf "\t with %d atoms, starting at line %d\n",n_atoms,line;
		i++;
	}
	else if ($2=="#W") {
		printf "no information found in %s\n",file;
		printf "\t with %d atoms, weight %d, starting at line %d\n",n_atoms,$3,line;
		i++;
                getline;
	}
	else if ($2=="##") {
		printf "generated from %s\n",$8;
		getline;
		gsub(":"," ");
		if ($2=="#W") {
		printf "\t with %d atoms, weight %d, starting at line %d\n",n_atoms,$3,line;
		getline;
		}
		else
		printf "\t with %d atoms, starting at line %d\n",n_atoms,line;
		i++;
	}
}'
